version: '3.8'

services:
  mysql:
    image: mysql:8.0.22
    container_name: mysql-hospital-queue
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker123
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: hospital-queue